baseURL = "https://cotice.eu/"
languageCode = "fr"
defaultContentLanguage = "fr"
title = "Association Cotice"

theme = "cotice-theme"

[params]
    author = "Association Cotice"
    description = "Association Cotice - Propose du housing, du BGP, des tunnels, du VPN pour des geeks, par des geeks."

    [params.navbar]
        name = "Cotice"
        url = "/"

        [[params.navbar.nav]]
        current = true
        name = "Accueil"
        url = "/"
        [[params.navbar.nav]]
        name = "Services"
        url = "/services"
        [[params.navbar.nav]]
        name = "Wiki"
        url = "https://wiki.cotice.eu"
    
    [params.header]
        name = "Association Cotice"
        tagline = "Du housing, du BGP, des tunnels, du VPN, pour des geeks, par des geeks."

    [params.summary]
        [params.summary.description]
        [[params.summary.description.items]]
        description = "Cotice est une association inscrite régie par les [articles 21 à 79-IV du code civil local maintenus en vigueur dans les départements du Bas-Rhin, Haut-Rhin et Moselle](https://fr.wikipedia.org/wiki/Association_de_droit_local_alsacien-mosellan), ayant pour but la promotion de l'interconnexion de réseaux informatiques."
        [[params.summary.description.items]]
        description = """### Actualités

* **2020-05-29** : Inscription au tribunal judiciaire de Metz.
* **2020-02-20** : Assemblée générale constitutive."""

        [params.summary.contact]
        name = "Association Cotice"
        address1 = "4 Rue du Roi Albert"
        address2 = "57070 Metz, France"
        phone = ""
        email = "contact@cotice.eu"
        twitter = "AssoCotice"

    [params.services]
        url = "/services"
        [params.services.description]
        [params.services.description.items]

[params.footer]
    copyright = "Hébergé par Cotice"
